// import { adventurer, adventurerNeutral, avataaars, avataaarsNeutral, bigEars, bigEarsNeutral, bigSmile, bottts, botttsNeutral, croodles, croodlesNeutral, funEmoji, icons, identicon, initials, lorelei, loreleiNeutral, micah, miniavs, notionists, notionistsNeutral, openPeeps, personas, pixelArt, pixelArtNeutral, rings, shapes, thumbs } from "@dicebear/collection";

// const styles = [
//     { "id": 1, "name": "Adventurer", "style": adventurer },
//     { "id": 2, "name": "Adventurer Neutral", "style": adventurerNeutral },
//     { "id": 3, "name": "Avataaars", "style": avataaars },
//     { "id": 4, "name": "Avataaars Neutral", "style": avataaarsNeutral },
//     { "id": 5, "name": "Big Ears", "style": bigEars },
//     { "id": 6, "name": "Big Ears Neutral", "style": bigEarsNeutral },
//     { "id": 7, "name": "Big Smile", "style": bigSmile },
//     { "id": 8, "name": "Bottts", "style": bottts },
//     { "id": 9, "name": "Bottts Neutral", "style": botttsNeutral },
//     { "id": 10, "name": "Croodles", "style": croodles },
//     { "id": 11, "name": "Croodles Neutral", "style": croodlesNeutral },
//     { "id": 12, "name": "Fun Emoji", "style": funEmoji },
//     { "id": 13, "name": "Icons", "style": icons },
//     { "id": 14, "name": "Identicon", "style": identicon },
//     { "id": 15, "name": "Initials", "style": initials },
//     { "id": 16, "name": "Lorelei", "style": lorelei },
//     { "id": 17, "name": "Lorelei Neutral", "style": loreleiNeutral },
//     { "id": 18, "name": "Micah", "style": micah },
//     { "id": 19, "name": "Miniavs", "style": miniavs },
//     { "id": 20, "name": "Notionists", "style": notionists },
//     { "id": 21, "name": "Notionists Neutral", "style": notionistsNeutral },
//     { "id": 22, "name": "Open Peeps", "style": openPeeps },
//     { "id": 23, "name": "Personas", "style": personas },
//     { "id": 24, "name": "Pixel Art", "style": pixelArt },
//     { "id": 25, "name": "Pixel Art Neutral", "style": pixelArtNeutral },
//     { "id": 26, "name": "Rings", "style": rings },
//     { "id": 27, "name": "Shapes", "style": shapes },
//     { "id": 28, "name": "Thumbs", "style": thumbs }
// ];

// export default styles;

import {
    adventurer,
    adventurerNeutral,
    avataaars,
    avataaarsNeutral,
    bigEars,
    bigEarsNeutral,
    bigSmile,
    bottts,
    botttsNeutral,
    croodles,
    croodlesNeutral,
    funEmoji,
    icons,
    identicon,
    initials,
    lorelei,
    loreleiNeutral,
    micah,
    miniavs,
    notionists,
    notionistsNeutral,
    openPeeps,
    personas,
    pixelArt,
    pixelArtNeutral,
    rings,
    shapes,
    thumbs,
} from "@dicebear/collection";

export const styleMap = {
    adventurer,
    adventurerNeutral,
    avataaars,
    avataaarsNeutral,
    bigEars,
    bigEarsNeutral,
    bigSmile,
    bottts,
    botttsNeutral,
    croodles,
    croodlesNeutral,
    funEmoji,
    icons,
    identicon,
    initials,
    lorelei,
    loreleiNeutral,
    micah,
    miniavs,
    notionists,
    notionistsNeutral,
    openPeeps,
    personas,
    pixelArt,
    pixelArtNeutral,
    rings,
    shapes,
    thumbs,
};

const styles = [
    { id: 1, name: "Adventurer", styleKey: "adventurer" },
    { id: 2, name: "Adventurer Neutral", styleKey: "adventurerNeutral" },
    { id: 3, name: "Avataaars", styleKey: "avataaars" },
    { id: 4, name: "Avataaars Neutral", styleKey: "avataaarsNeutral" },
    { id: 5, name: "Big Ears", styleKey: "bigEars" },
    { id: 6, name: "Big Ears Neutral", styleKey: "bigEarsNeutral" },
    { id: 7, name: "Big Smile", styleKey: "bigSmile" },
    { id: 8, name: "Bottts", styleKey: "bottts" },
    { id: 9, name: "Bottts Neutral", styleKey: "botttsNeutral" },
    { id: 10, name: "Croodles", styleKey: "croodles" },
    { id: 11, name: "Croodles Neutral", styleKey: "croodlesNeutral" },
    { id: 12, name: "Fun Emoji", styleKey: "funEmoji" },
    { id: 13, name: "Icons", styleKey: "icons" },
    { id: 14, name: "Identicon", styleKey: "identicon" },
    { id: 15, name: "Initials", styleKey: "initials" },
    { id: 16, name: "Lorelei", styleKey: "lorelei" },
    { id: 17, name: "Lorelei Neutral", styleKey: "loreleiNeutral" },
    { id: 18, name: "Micah", styleKey: "micah" },
    { id: 19, name: "Miniavs", styleKey: "miniavs" },
    { id: 20, name: "Notionists", styleKey: "notionists" },
    { id: 21, name: "Notionists Neutral", styleKey: "notionistsNeutral" },
    { id: 22, name: "Open Peeps", styleKey: "openPeeps" },
    { id: 23, name: "Personas", styleKey: "personas" },
    { id: 24, name: "Pixel Art", styleKey: "pixelArt" },
    { id: 25, name: "Pixel Art Neutral", styleKey: "pixelArtNeutral" },
    { id: 26, name: "Rings", styleKey: "rings" },
    { id: 27, name: "Shapes", styleKey: "shapes" },
    { id: 28, name: "Thumbs", styleKey: "thumbs" },
];

export default styles;
